### ISSUE TITLE
ID 9:"Als gebruiker wil ik mijn orderhistorie kunnen inzien zodat ik  informatie over mijn besteld producten kan terugvinden."

### ISSUE THREAD

**Issue by DilanOnCode** [barld/project5_6#21]
"- Maak een orderhistorie pagina
- Haal de order op uit de database
- Toon orders op volgorde van aankoopdatum"

**Comment by BrutalCoding** [comment]
Is dit inmiddels al gedaan? Volgens mij was @JFConstancia hier mee bezig

**Comment by barld** [comment]
Hebben we touch gedaan. Allen sortereren zou me not explicitly kunnen maken
