### ISSUE TITLE
ID 10:"Als gebruiker wil ik gekochte producten kunnen toevoegen  aan een favorieten lijst zodat ik mijn favoriete producten  snel kan terugvinden."

### ISSUE THREAD

**Issue by DilanOnCode** [barld/project5_6#22]
"- Maak een favorieten lijst 
- Voeg een knop toe aan de orderhistorie om producten toe
 te kunnen voegen aan de favorietenlijst"

**Comment by BrutalCoding** [comment]
Dit werkt, maar net zoals bij de Wish List zijn de items niet klikbaar om ze snel terug te vinden.
