### ISSUE TITLE
ID 11:"Als gebruiker wil ik producten kunnen toevoegen aan een  wenslijst zodat ik deze later kan bestellen."

### ISSUE THREAD

**Issue by DilanOnCode** [barld/project5_6#23]
"- Maak een wenslijst
- Voeg een knop toe aan de productinformatie pagina om 
producten toe te kunnen voegen aan de wenslijst"

**Comment by BrutalCoding** [comment]
Er er is geen link of iets dergelijks per item in de Wish List, dus de gebruiker kan niet op een game klikken om het vervolgens opnieuw te bestellen. Alleen de naam van de game is zichtbaar, dus dan zou de gebruiker de game handmatig opnieuw moeten zoeken.
