### ISSUE TITLE
ID 12:"Als gebruiker wil ik kunnen bepalen of mijn wenslijst privé of  publiekelijk is zodat ik zelf kan bepalen wat ik andere  mensen kunnen zien."

### ISSUE THREAD

**Issue by DilanOnCode** [barld/project5_6#24]
"- Voeg een keuze toe aan de wenslijst
- Zodra de gebruiker de status wijzigd wordt dit direct toegepast"

**Comment by BrutalCoding** [comment]
Status kan worden bijgehouden in de database, meer niet dus deze feature is nog niet af.
